version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sgh0806Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: AddPublicService
  gitServerName: srcCtrl_gitlab_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlab
  gitUsername: ArtiKhareGitlab
  gitBranch: master
